# -*- mode: ansible -*-
# vi: set ft=ansible :
---
- hosts: exeggutor-box
  sudo: True
  tasks:
    - name: get dot-files for vagrant
      command: git clone --recursive git://github.com/casualjim/dot-files.git creates=/home/vagrant/dot-files chdir=/home/vagrant
      register: got_dot_files

    - name: set vagrant as owner for dot-files
      file: path=/home/vagrant/dot-files owner=vagrant group=vagrant recurse=yes state=directory

    - name: install dependencies for youcompleteme 
      apt: state=present name={{item}}
      when: got_dot_files.changed
      with_items:
        - cmake
        - python-dev
        - clang
        - libclang-dev

    - name: set up dot-files for vagrant
      shell: /home/vagrant/dot-files/setup.sh chdir=/home/vagrant/dot-files
      when: got_dot_files.changed

    - name: download godeb
      get_url: url=https://godeb.s3.amazonaws.com/godeb-amd64.tar.gz dest=/tmp/godeb-amd64.tar.gz
      register: godeb_download

    - name: extract godeb
      command: tar -zxf /tmp/godeb-amd64.tar.gz -C /usr/bin
      when: godeb_download.changed
      
    - name: install golang 1.3
      command: /usr/bin/godeb install 1.3 chdir=/tmp
      when: godeb_download.changed

    - name: install exeggutor dependencies from apt
      apt: name={{item}} state=present
      with_items:
        - mercurial
        - libprotobuf-dev
        - protobuf-compiler
        - nodejs
        - npm

    - name: install npm packages
      npm: name={{item}} global=yes
      with_items:
        - grunt-cli 
        - karma 
        - bower
        
      


    

