# -*- mode: ansible -*-
# vi: set ft=ansible :
---
- hosts: exeggutor-box
  sudo: True
  tasks:
    - name: get dot-files for vagrant
      command: git clone --recursive git://github.com/casualjim/dot-files.git creates=/home/vagrant/dot-files chdir=/home/vagrant
      register: got_dot_files

    - name: set vagrant as owner for dot-files
      file: path=/home/vagrant/dot-files owner=vagrant group=vagrant recurse=yes state=directory

    - name: install dependencies for youcompleteme 
      apt: state=present name={{item}}
      when: got_dot_files.changed
      with_items:
        - cmake
        - python-dev
        - clang
        - libclang-dev

    - name: set up dot-files for vagrant
      shell: ./setup.sh chdir=/home/vagrant/dot-files
      when: got_dot_files.changed
    

